### ISSUE TITLE
videoWriter error

### ISSUE THREAD

**Issue by rhaizer** [Dylan-H-Wang/SLF-RPM#1]
I tried running this both on macbook pro and google colab. both of them giving videoIO related errors.

Macbook:

```
=> Use device cpu for demo

=> Creating SLF-RPM Classifier Model: 3D ResNet-18
=> Loading model weights './mahnob_best.pth'
=> Loaded model weights './mahnob_best.pth
[h264_videotoolbox @ 0x7fcc513e0c00] Error: cannot create compression session: -12903
[h264_videotoolbox @ 0x7fcc513e0c00] Try -allow_sw 1. The hardware encoder may be busy, or not supported.
[ERROR:0] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2794) open Could not open codec h264_videotoolbox, error: Unspecified error
[ERROR:0] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2811) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/videoio/src/cap.cpp (597) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.4) /Users/runner/work/opencv-python/opencv-python/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /var/folders/hw/n137g9rs2yd3c7pyhrp6y6rm0000gn/T/video_format_test5z3v418n/test_file.mkv in function 'icvExtractPattern'


  0%|                                                                                                   | 0/1228 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 242, in <module>
    for vis_frame in tqdm(processor.run(video), total=num_frames):
  File "/Users/aaa/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 149, in run
    b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

google colab:

```
=> Use device cuda:0 for demo

=> Creating SLF-RPM Classifier Model: 3D ResNet-18
=> Loading model weights './ubfc_best.pth'
=> Loaded model weights './ubfc_best.pth
Could not find encoder for codec id 27: Encoder not found
[ERROR:0] global /io/opencv/modules/videoio/src/cap.cpp (392) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.1.2) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /tmp/video_format_test65vzqlik/test_file.mkv in function 'icvExtractPattern'


  0% 0/614 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 241, in <module>
    for vis_frame in tqdm(processor.run(video), total=num_frames):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "demo.py", line 148, in run
    b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Could you please consider adding a module for json/csv output for hr result? IMO, video output is not necessary if it's the thing causing the error.

**Comment by Dylan-H-Wang** [comment]
Hi rhaizer,

This `demo.py` file is modified from [detectron2](https://github.com/facebookresearch/detectron2/blob/main/demo/demo.py). From you log file, it seems like `opencv` cannot read `.mkv` format videos, maybe you can try other format e.g., `mp4`.

If you need text output only, please try `test.py` which prints results in the terminal and you can redirect it to a text file. The `demo.py` is for visualisation purpose.

Cheers

**Comment by rhaizer** [comment]
> Hi rhaizer,
> 
> This `demo.py` file is modified from [detectron2](https://github.com/facebookresearch/detectron2/blob/main/demo/demo.py). From you log file, it seems like `opencv` cannot read `.mkv` format videos, maybe you can try other format e.g., `mp4`.
> 
> If you need text output only, please try `test.py` which prints results in the terminal and you can redirect it to a text file. The `demo.py` is for visualisation purpose.
> 
> Cheers

Thanks for the quick response. I don't know why it specifies a `.mkv` formatted video but the type of the videos are `.mov` or `.mp4`I tried at least 10 different videos and 3 different computer/OS's but no luck. 

I also tried --webcam input this time it gives this error:

```
=> Use device cpu for demo

=> Creating SLF-RPM Classifier Model: 3D ResNet-18
=> Loading model weights './mahnob_best.pth'
=> Loaded model weights './mahnob_best.pth
0it [00:05, ?it/s]
Traceback (most recent call last):
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 261, in <module>
    for vis in tqdm(processor.run(cam)):
  File "/Users/aaa/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 149, in run
    b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indice
```
For your suggestion, looks like `test.py ` is really different than the demo.py. It is expecting a series of frames in a certain format. I will continue to try to make it work. Thank you for the repo!

P.s. A docker image would be really nice to test this. If I manage to make it work I will dockerize it then share it in a fork of this repo.

**Comment by rhaizer** [comment]
I solved the first opencv error by playing with `test_opencv_video_format`

```
def test_opencv_video_format(codec, file_ext):
    with tempfile.TemporaryDirectory(prefix="video_format_test") as dir:
        filename = os.path.join(dir, "test_file" + '.mp4')
```

Now I get the same error as the webcam input:
```

Traceback (most recent call last):
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 242, in <module>
    for vis_frame in tqdm(processor.run(video), total=num_frames):
  File "/Users/aaa/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 149, in run
    b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
``` @Dylan-H-Wang

**Comment by rhaizer** [comment]
> I solved the first opencv error by playing with `test_opencv_video_format`
> 
> ```
> def test_opencv_video_format(codec, file_ext):
>     with tempfile.TemporaryDirectory(prefix="video_format_test") as dir:
>         filename = os.path.join(dir, "test_file" + '.mp4')
> ```
> 
> Now I get the same error as the webcam input:
> 
> ```
> 
> Traceback (most recent call last):
>   File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 242, in <module>
>     for vis_frame in tqdm(processor.run(video), total=num_frames):
>   File "/Users/aaa/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
>     for obj in iterable:
>   File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 149, in run
>     b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> ```
> 
> @Dylan-H-Wang

I solved this one by converting necessary parts to int because indexes can not be float. The following modiciation fixed the issue.

```

                b1, g1, r1 = ori_clip[idx][int(forehead_idx[0][0][0]), int(forehead_idx[0][0][1])]/255
                b2, g2, r2 = ori_clip[idx][int(left_cheek_idx[0][0][0]), int(left_cheek_idx[0][0][1])]/255
                b3, g3, r3 = ori_clip[idx][int(right_cheek_idx[0][0][0]), int(right_cheek_idx[0][0][1])]/255
                b4, g4, r4 = ori_clip[idx][int(mouth_idx[0][0][0]), int(mouth_idx[0][0][1])]/255

                cv2.polylines(ori_clip[idx], np.int32([forehead_idx]), True, (0, 102, 102))
                cv2.polylines(ori_clip[idx], np.int32([left_cheek_idx]), True, (255, 128, 0))
                cv2.polylines(ori_clip[idx], np.int32([right_cheek_idx]), True, (255, 102, 102))
                cv2.polylines(ori_clip[idx], np.int32([mouth_idx]), True, (51, 153, 255))

                cv2.line(ori_clip[idx], (50, 50), (50-int(10*b1),50),(0, 102, 102),1)
                cv2.line(ori_clip[idx], (50, 52), (50-int(10*g1),52),(0, 102, 102),1)
                cv2.line(ori_clip[idx], (50, 54), (50-int(10*r1),54),(0, 102, 102),1)

                cv2.line(ori_clip[idx], (150, 50), (150-int(10*b2),50),(255, 128, 0),1)
                cv2.line(ori_clip[idx], (150, 52), (150-int(10*g2),52),(255, 128, 0),1)
                cv2.line(ori_clip[idx], (150, 54), (150-int(10*r2),54),(255, 128, 0),1)

                cv2.line(ori_clip[idx], (250, 50), (250-int(10*b3),50),(255, 102, 102),1)
                cv2.line(ori_clip[idx], (250, 52), (250-int(10*g3),52),(255, 102, 102),1)
                cv2.line(ori_clip[idx], (250, 54), (250-int(10*r3),54),(255, 102, 102),1)

                cv2.line(ori_clip[idx], (350, 50), (350-int(10*b4),50),(51, 153, 255),1)
                cv2.line(ori_clip[idx], (350, 52), (350-int(10*g4),52),(51, 153, 255),1)
                cv2.line(ori_clip[idx], (350, 54), (350-int(10*r4),54),(51, 153, 255),1)
```

However facial landmarks are being rendered at the wrong place. I tried different videos. It looks like it always go for the right shoulder so I assume there is some rotation issue. Is there any rotation in the input video expected? The HR values are so bad so I think this area is also being used on the calculation not just for rendering.

**Comment by Dylan-H-Wang** [comment]
> > I solved the first opencv error by playing with `test_opencv_video_format`
> > ```
> > def test_opencv_video_format(codec, file_ext):
> >     with tempfile.TemporaryDirectory(prefix="video_format_test") as dir:
> >         filename = os.path.join(dir, "test_file" + '.mp4')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now I get the same error as the webcam input:
> > ```
> > 
> > Traceback (most recent call last):
> >   File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 242, in <module>
> >     for vis_frame in tqdm(processor.run(video), total=num_frames):
> >   File "/Users/aaa/opt/anaconda3/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
> >     for obj in iterable:
> >   File "/Users/aaa/Documents/emoty/GIT/RPPG/SLF-RPM-main/demo.py", line 149, in run
> >     b1, g1, r1 = ori_clip[idx][forehead_idx[0][0][0], forehead_idx[0][0][1]]/255
> > IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @Dylan-H-Wang
> 
> I solved this one by converting necessary parts to int because indexes can not be float. The following modiciation fixed the issue.
> 
> ```
> 
>                 b1, g1, r1 = ori_clip[idx][int(forehead_idx[0][0][0]), int(forehead_idx[0][0][1])]/255
>                 b2, g2, r2 = ori_clip[idx][int(left_cheek_idx[0][0][0]), int(left_cheek_idx[0][0][1])]/255
>                 b3, g3, r3 = ori_clip[idx][int(right_cheek_idx[0][0][0]), int(right_cheek_idx[0][0][1])]/255
>                 b4, g4, r4 = ori_clip[idx][int(mouth_idx[0][0][0]), int(mouth_idx[0][0][1])]/255
> 
>                 cv2.polylines(ori_clip[idx], np.int32([forehead_idx]), True, (0, 102, 102))
>                 cv2.polylines(ori_clip[idx], np.int32([left_cheek_idx]), True, (255, 128, 0))
>                 cv2.polylines(ori_clip[idx], np.int32([right_cheek_idx]), True, (255, 102, 102))
>                 cv2.polylines(ori_clip[idx], np.int32([mouth_idx]), True, (51, 153, 255))
> 
>                 cv2.line(ori_clip[idx], (50, 50), (50-int(10*b1),50),(0, 102, 102),1)
>                 cv2.line(ori_clip[idx], (50, 52), (50-int(10*g1),52),(0, 102, 102),1)
>                 cv2.line(ori_clip[idx], (50, 54), (50-int(10*r1),54),(0, 102, 102),1)
> 
>                 cv2.line(ori_clip[idx], (150, 50), (150-int(10*b2),50),(255, 128, 0),1)
>                 cv2.line(ori_clip[idx], (150, 52), (150-int(10*g2),52),(255, 128, 0),1)
>                 cv2.line(ori_clip[idx], (150, 54), (150-int(10*r2),54),(255, 128, 0),1)
> 
>                 cv2.line(ori_clip[idx], (250, 50), (250-int(10*b3),50),(255, 102, 102),1)
>                 cv2.line(ori_clip[idx], (250, 52), (250-int(10*g3),52),(255, 102, 102),1)
>                 cv2.line(ori_clip[idx], (250, 54), (250-int(10*r3),54),(255, 102, 102),1)
> 
>                 cv2.line(ori_clip[idx], (350, 50), (350-int(10*b4),50),(51, 153, 255),1)
>                 cv2.line(ori_clip[idx], (350, 52), (350-int(10*g4),52),(51, 153, 255),1)
>                 cv2.line(ori_clip[idx], (350, 54), (350-int(10*r4),54),(51, 153, 255),1)
> ```
> 
> However facial landmarks are being rendered at the wrong place. I tried different videos. It looks like it always go for the right shoulder so I assume there is some rotation issue. Is there any rotation in the input video expected? The HR values are so bad so I think this area is also being used on the calculation not just for rendering.
> 
> https://imgur.com/BvEdBEB

I appreciate your helps for the bug!
It seems like I have not uploaded correct version of this file, and unfortunately the computer hosting this repo is crashed and it needs some time to back online. By the way, as I wrote in the `README`, this demo only supports single input file, and I have not tested the webcam function.

For your mentioned problem, actually there is one solution that you can comment out all of visualisation codes since they are nothing to do with the predictions. Then, there will be HR outputs in your terminal.

For the bad performance, this repo provides unsupervised pre-trained model only, so you need some downstream task training to make predictions.

**Comment by italosalgado14** [comment]
Hello. When implementing the model I found the same problem (and the same solution). With regard to the quality of the measurements, the same thing has happened to me (low quality results). Could the face detector be  malfunctioning?
![example](https://user-images.githubusercontent.com/55506775/166819537-2dd622f6-cc15-4e98-95b9-ceb0edb8c681.png)

**Comment by Dylan-H-Wang** [comment]
> Hello. When implementing the model I found the same problem (and the same solution). With regard to the quality of the measurements, the same thing has happened to me (low quality results). Could the face detector be malfunctioning? ![example](https://user-images.githubusercontent.com/55506775/166819537-2dd622f6-cc15-4e98-95b9-ceb0edb8c681.png)
> 
> * test_output.log
>   ....
>   [2022-05-04 10:07:11,393] INFO: Model saved at epoch 66
>   ....
>   [2022-05-04 10:13:04,533] INFO: (100/100) Test Train Loss: 18.2698, Test Val Loss/Best: 12.0483/11.7305, Test SD: 14.2368, Test RMSE: 14.2327, Test R: 0.1732

There is a bug in the demo code, which is not related to the actual working codes, please ignore it. 
Are you running with
```bash
python test.py --gpu 0 --epochs 100 --batch_size 128 --lr 5e-3 --dropout 0 \
	--pretrained "./logs/ubfc/train/best_train_model.pth.tar" \
	--dataset_name "ubfc-rppg" \
	--dataset_dir "path/to/dataset" \
	--workers 4 --vid_frame 150 --vid_frame_stride 2 \
	--log_dir "./logs/ubfc/test" \
	--model_depth 18
```
where the best model is from the repo [link](https://github.com/Dylan-H-Wang/SLF-RPM/releases/download/v1.0/ubfc_best.pth)?

**Comment by italosalgado14** [comment]
hello,
i tested them (the repo link), but the models dont match: error in charge the parameters in the file demo.py:
```
print(f"=> Loading model weights '{args.pretrained}'")
checkpoint = torch.load(args.pretrained, map_location="cpu")
state_dict = checkpoint["state_dict"]
self.model.load_state_dict(state_dict)   <-----------error
print(f"=> Loaded model weights '{args.pretrained}")
``` 
The model:
```
self.model = classifier.LinearClsResNet3D(model_depth=18, n_class=1) # 3d resnet 18
```
and the error:
```
python demo.py --pretrained "ubfc_best.pth" --input  "test_videos/vid.avi"

=> Use device cuda:0 for demo

=> Creating SLF-RPM Classifier Model: 3D ResNet-18
=> Loading model weights 'ubfc_best.pth'
Traceback (most recent call last):
  File "demo.py", line 216, in <module>
    processor = DemoProcessor(args)
  File "demo.py", line 77, in __init__
    self.predictor = Predictor(args)
  File "demo.py", line 32, in __init__
    self._build_model(args)
  File "demo.py", line 45, in _build_model
    self.model.load_state_dict(state_dict)
  File "/home/laila/.pyenv/versions/3.8.13/envs/SLF-RPM/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LinearClsResNet3D:
        Missing key(s) in state_dict: "encoder_q.fc.weight", "encoder_q.fc.bias". 
        Unexpected key(s) in state_dict: "proj_head.0.weight", "proj_head.0.bias", "proj_head.2.weight", "proj_head.2.bias", "spatial_classifer.weight", "spatial_classifer.bias", "temporal_classifer.weight", "temporal_classifer.bias". 
```

I'm a little confused what is the pretrained model :(

P.S.  For my train i use
```
# UBFC
python main.py --gpu 0 --epochs 100  --batch_size 64 --lr 1e-4 \
	--n_dim 2048 --temperature 0.1 \
	--dataset_name "ubfc-rppg" \
	--dataset_dir "ubfc-rppg/" \
	--workers 4 --vid_frame 150 --clip_frame 30 --roi_list 0 1 2 3 4 5 6 --stride_list 1 2 3 4 5 \
	--log_dir "./logs/ubfc/train" \
	--model_depth 18


python test.py --gpu 0 --epochs 100 --batch_size 64 --lr 5e-3 --dropout 0 \
	--pretrained "./logs/ubfc/train/best_train_model.pth.tar" \
	--dataset_name "ubfc-rppg" \
	--dataset_dir "ubfc-rppg/" \
	--workers 4 --vid_frame 150 --vid_frame_stride 2 \
	--log_dir "./logs/ubfc/test" \
	--model_depth 18

python demo.py --pretrained "ubfc_best.pth" --input  "test_videos/vid.avi"
```

same as you but with batch_size 64.

**Comment by Dylan-H-Wang** [comment]
You are misunderstanding the usage of pretrained model.

This repo provides only SSL-pretrained models instead of fine-tuned models, you should train it by yourself. That is to say you can use 
```python
# UBFC
python test.py --gpu 0 --epochs 100 --batch_size 128 --lr 5e-3 --dropout 0 \
	--pretrained "ubfc_best.pth" \ # download from this repo
	--dataset_name "ubfc-rppg" \
	--dataset_dir "path/to/dataset" \
	--workers 4 --vid_frame 150 --vid_frame_stride 2 \
	--log_dir "./logs/ubfc/test" \
	--model_depth 18

python demo.py --pretrained "weights/from/./logs/ubfc/test" --input  "test_videos/vid.avi"
```

**Comment by italosalgado14** [comment]
(sorry for the delay) Its works! I adapt the test.py code. I convert my video with the converter of the repo, and adapt the code of --evaluate flag. Now i compare results with an pulse oximeter (HR). I'll let you know how it went after testing. Now I try with .mov (I don't know very well if this affects) files with differents qualities (FHD, 4K?). Thx 4 everything!

**Comment by Dylan-H-Wang** [comment]
> (sorry for the delay) Its works! I adapt the test.py code. I convert my video with the converter of the repo, and adapt the code of --evaluate flag. Now i compare results with an pulse oximeter (HR).

Thank you for the update!

Just forgot to comment that I closed this issue because I removed the `demo.py` since it seems to cause confusions and I do not have enough time to fix them. Now the repo only contains codes to help you replicate the paper results. Anything related to the demo, please create discussion [here](https://github.com/Dylan-H-Wang/SLF-RPM/discussions/new), since this is not related to code bugs. Thanks!
